# version: '3.8'

networks:
  orapay-net:
    driver: bridge

volumes:
  postgres_data:
  grafana_data:

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: orapay_db
      POSTGRES_USER: ozy
      POSTGRES_PASSWORD: Ozy@000
    networks:
      - orapay-net
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ozy -d orapay_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis
    networks:
      - orapay-net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/orapay_db
      SPRING_DATASOURCE_USERNAME: ozy
      SPRING_DATASOURCE_PASSWORD: Ozy@000
      SPRING_DATA_REDIS_HOST: redis
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - orapay-net

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - orapay-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - orapay-net

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    networks:
      - orapay-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - orapay-net